### ISSUE TITLE
Vendoring additional cookbooks after first install

### ISSUE THREAD

**Issue by erez-rabih** [Youscribe/htpasswd-cookbook#17]
Hi,

I am using Berkshelf in order to manage my pool of community cookbooks on chef-repo/vendor/cookbooks directory
First I ran the vendor command in order to install all cookbooks in the Berksfile. Now I added an additional cookbook but when I try to vendor it Berkshelf raises an error saying the directory /vendor/cookbooks already exists.
What is the right way to add a cookbook to the vendor directory? Am I really expected to completely delete all the /vendor/cookbook directory and run berks vendor again?
Thanks for the help :)

**Comment by mburns** [comment]
What you're describing is a berkshelf bug/behavior, not htpasswd in particular. We should close this issue.

In any event, the behavior you're describing is [intentional](https://github.com/berkshelf/berkshelf/issues/785#issuecomment-21956341), though in my case berks overwrites the directory each time. You should maybe upgrade your version of `berks` (3.2.4 is the latest).

The way to add a vendor cookbook is to first add the entry in `Berksfile` and then, in your case, delete the directory you're going to download into before running `berks vendor`. Since you should never be editing any file in the berkshelf directly, regenerating the directory should always work the same way.

```shell
cd chef-repo
#edit Berksfile
rm -rf vendor/cookbooks
berks vendor vendor/cookbooks
```

**Comment by guilhem** [comment]
Thanks @mburns for this answer :)

@erez-rabih I'm closing this issue, don't hesitate to re-open / comment if any problem
